using Terraria;
using Terraria.ID;

namespace RainOverhaul.Content {
    public class RainTile {
        /// <summary>
		/// List of vanilla tiles, that can't protect entity from the rain. 
		/// </summary>
        public bool CantProtectVanilla(Tile tTile) {
            return 
            tTile.TileType==TileID.Dirt||tTile.TileType==TileID.Grass||tTile.TileType==TileID.Plants||tTile.TileType==TileID.Torches||
            tTile.TileType==TileID.Trees||tTile.TileType==TileID.ClosedDoor||tTile.TileType==TileID.OpenDoor||tTile.TileType==TileID.Heart||
            tTile.TileType==TileID.Bottles||tTile.TileType==TileID.Tables||tTile.TileType==TileID.Chairs||tTile.TileType==TileID.Anvils||
            tTile.TileType==TileID.Furnaces||tTile.TileType==TileID.WorkBenches||tTile.TileType==TileID.Platforms||tTile.TileType==TileID.Saplings||
            tTile.TileType==TileID.Containers||tTile.TileType==TileID.CorruptGrass||tTile.TileType==TileID.CorruptPlants||tTile.TileType==TileID.DemonAltar||
            tTile.TileType==TileID.Sunflower||tTile.TileType==TileID.Pots||tTile.TileType==TileID.PiggyBank||tTile.TileType==TileID.WoodBlock||tTile.TileType==TileID.ShadowOrbs||
            tTile.TileType==TileID.CorruptThorns||tTile.TileType==TileID.Candles||tTile.TileType==TileID.Chandeliers||tTile.TileType==TileID.Jackolanterns||
            tTile.TileType==TileID.Presents||tTile.TileType==TileID.ClayBlock||tTile.TileType==TileID.HangingLanterns||tTile.TileType==TileID.Spikes||
            tTile.TileType==TileID.WaterCandle||tTile.TileType==TileID.Books||tTile.TileType==TileID.Cobweb||tTile.TileType==TileID.Vines||
            tTile.TileType==TileID.Sand||tTile.TileType==TileID.Signs||tTile.TileType==TileID.Ash||tTile.TileType==TileID.Mud||
            tTile.TileType==TileID.JungleGrass||tTile.TileType==TileID.JunglePlants||tTile.TileType==TileID.JungleVines||tTile.TileType==TileID.JungleThorns||
            tTile.TileType==TileID.MushroomGrass||tTile.TileType==TileID.MushroomPlants||tTile.TileType==TileID.MushroomTrees||tTile.TileType==TileID.Plants2||
            tTile.TileType==TileID.JunglePlants2||tTile.TileType==TileID.Hellforge||tTile.TileType==TileID.ClayPot||tTile.TileType==TileID.Beds||
            tTile.TileType==TileID.Cactus||tTile.TileType==TileID.Coral||tTile.TileType==TileID.ImmatureHerbs||tTile.TileType==TileID.MatureHerbs||
            tTile.TileType==TileID.BloomingHerbs||tTile.TileType==TileID.Tombstones||tTile.TileType==TileID.Loom||tTile.TileType==TileID.Pianos||
            tTile.TileType==TileID.Dressers||tTile.TileType==TileID.Benches||tTile.TileType==TileID.Bathtubs||tTile.TileType==TileID.Banners||
            tTile.TileType==TileID.Lampposts||tTile.TileType==TileID.Lamps||tTile.TileType==TileID.Kegs||tTile.TileType==TileID.ChineseLanterns||
            tTile.TileType==TileID.CookingPots||tTile.TileType==TileID.Safes||tTile.TileType==TileID.SkullLanterns||tTile.TileType==TileID.TrashCan||
            tTile.TileType==TileID.Candelabras||tTile.TileType==TileID.Bookcases||tTile.TileType==TileID.Thrones||tTile.TileType==TileID.Bowls||
            tTile.TileType==TileID.GrandfatherClocks||tTile.TileType==TileID.Statues||tTile.TileType==TileID.Sawmill||tTile.TileType==TileID.HallowedGrass||
            tTile.TileType==TileID.HallowedPlants||tTile.TileType==TileID.Ebonsand||tTile.TileType==TileID.HallowedPlants2||tTile.TileType==TileID.TinkerersWorkbench||
            tTile.TileType==TileID.HallowedVines||tTile.TileType==TileID.Pearlsand||tTile.TileType==TileID.Silt||tTile.TileType==TileID.WoodenBeam||
            tTile.TileType==TileID.CrystalBall||tTile.TileType==TileID.DiscoBall||tTile.TileType==TileID.MagicalIceBlock||tTile.TileType==TileID.Mannequin||
            tTile.TileType==TileID.Crystals||tTile.TileType==TileID.InactiveStoneBlock||tTile.TileType==TileID.Lever||tTile.TileType==TileID.AdamantiteForge||
            tTile.TileType==TileID.MythrilAnvil||tTile.TileType==TileID.PressurePlates||tTile.TileType==TileID.Switches||tTile.TileType==TileID.Traps||
            tTile.TileType==TileID.Boulder||tTile.TileType==TileID.MusicBoxes||tTile.TileType==TileID.Explosives||tTile.TileType==TileID.InletPump||
            tTile.TileType==TileID.OutletPump||tTile.TileType==TileID.Timers||tTile.TileType==TileID.SnowBlock||tTile.TileType==TileID.SnowBrick||tTile.TileType==TileID.CandyCaneBlock||
            tTile.TileType==TileID.GreenCandyCaneBlock||tTile.TileType==TileID.HolidayLights||tTile.TileType==TileID.Ebonwood||tTile.TileType==TileID.RichMahogany||tTile.TileType==TileID.Pearlwood||
            tTile.TileType==TileID.BreakableIce||tTile.TileType==TileID.Stalactite||tTile.TileType==TileID.PineTree||tTile.TileType==TileID.ChristmasTree||
            tTile.TileType==TileID.Sinks||tTile.TileType==TileID.PlatinumCandelabra||tTile.TileType==TileID.PlatinumCandle||tTile.TileType==TileID.ExposedGems||
            tTile.TileType==TileID.LongMoss||tTile.TileType==TileID.SmallPiles||tTile.TileType==TileID.LargePiles||tTile.TileType==TileID.LargePiles2||
            tTile.TileType==TileID.CactusBlock||tTile.TileType==TileID.Cloud||tTile.TileType==TileID.MushroomBlock||tTile.TileType==TileID.LivingWood||tTile.TileType==TileID.LeafBlock||
            tTile.TileType==TileID.SlimeBlock||tTile.TileType==TileID.BoneBlock||tTile.TileType==TileID.FleshBlock||tTile.TileType==TileID.RainCloud||
            tTile.TileType==TileID.CrimsonGrass||tTile.TileType==TileID.CrimsonPlants||tTile.TileType==TileID.CrimsonVines||tTile.TileType==TileID.WaterFountain||
            tTile.TileType==TileID.Cannon||tTile.TileType==TileID.LandMine||tTile.TileType==TileID.SnowballLauncher||tTile.TileType==TileID.Rope||
            tTile.TileType==TileID.Chain||tTile.TileType==TileID.Campfire||tTile.TileType==TileID.Firework||tTile.TileType==TileID.Blendomatic||
            tTile.TileType==TileID.MeatGrinder||tTile.TileType==TileID.Extractinator||tTile.TileType==TileID.Solidifier||tTile.TileType==TileID.Slush||tTile.TileType==TileID.Hive||
            tTile.TileType==TileID.DyePlants||tTile.TileType==TileID.DyeVat||tTile.TileType==TileID.HoneyBlock||tTile.TileType==TileID.CrispyHoneyBlock||
            tTile.TileType==TileID.Larva||tTile.TileType==TileID.WoodenSpikes||tTile.TileType==TileID.PlantDetritus||tTile.TileType==TileID.Crimsand||
            tTile.TileType==TileID.Teleporter||tTile.TileType==TileID.LifeFruit||tTile.TileType==TileID.LihzahrdAltar||tTile.TileType==TileID.PlanteraBulb||
            tTile.TileType==TileID.MetalBars||tTile.TileType==TileID.Painting3X3||tTile.TileType==TileID.Painting4X3||tTile.TileType==TileID.Painting6X4||
            tTile.TileType==TileID.ImbuingStation||tTile.TileType==TileID.BubbleMachine||tTile.TileType==TileID.Painting2X3||tTile.TileType==TileID.Painting3X2||
            tTile.TileType==TileID.Autohammer||tTile.TileType==TileID.PumpkinBlock||tTile.TileType==TileID.HayBlock||tTile.TileType==TileID.SpookyWood||tTile.TileType==TileID.Pumpkins||
            tTile.TileType==TileID.Womannequin||tTile.TileType==TileID.FireflyinaBottle||tTile.TileType==TileID.LightningBuginaBottle||tTile.TileType==TileID.Cog||
            tTile.TileType==TileID.BunnyCage||tTile.TileType==TileID.SquirrelCage||tTile.TileType==TileID.MallardDuckCage||tTile.TileType==TileID.DuckCage||
            tTile.TileType==TileID.BlueJay||tTile.TileType==TileID.CardinalCage||tTile.TileType==TileID.FishBowl||tTile.TileType==TileID.HeavyWorkBench||
            tTile.TileType==TileID.SnailCage||tTile.TileType==TileID.GlowingSnailCage||tTile.TileType==TileID.AmmoBox||tTile.TileType==TileID.MonarchButterflyJar||
            tTile.TileType==TileID.PurpleEmperorButterflyJar||tTile.TileType==TileID.RedAdmiralButterflyJar||tTile.TileType==TileID.UlyssesButterflyJar||tTile.TileType==TileID.SulphurButterflyJar||
            tTile.TileType==TileID.TreeNymphButterflyJar||tTile.TileType==TileID.ZebraSwallowtailButterflyJar||tTile.TileType==TileID.JuliaButterflyJar||tTile.TileType==TileID.ScorpionCage||
            tTile.TileType==TileID.BlackScorpionCage||tTile.TileType==TileID.FrogCage||tTile.TileType==TileID.MouseCage||tTile.TileType==TileID.BoneWelder||
            tTile.TileType==TileID.FleshCloningVat||tTile.TileType==TileID.GlassKiln||tTile.TileType==TileID.LihzahrdFurnace||tTile.TileType==TileID.LivingLoom||
            tTile.TileType==TileID.SkyMill||tTile.TileType==TileID.IceMachine||tTile.TileType==TileID.SteampunkBoiler||tTile.TileType==TileID.HoneyDispenser||
            tTile.TileType==TileID.PenguinCage||tTile.TileType==TileID.WormCage||tTile.TileType==TileID.DynastyWood||tTile.TileType==TileID.MinecartTrack||tTile.TileType==TileID.Coralstone||
            tTile.TileType==TileID.BlueJellyfishBowl||tTile.TileType==TileID.GreenJellyfishBowl||tTile.TileType==TileID.PinkJellyfishBowl||tTile.TileType==TileID.ShipInABottle||
            tTile.TileType==TileID.SeaweedPlanter||tTile.TileType==TileID.BorealWood||tTile.TileType==TileID.PalmWood||tTile.TileType==TileID.PalmTree||
            tTile.TileType==TileID.BeachPiles||tTile.TileType==TileID.Waterfall||tTile.TileType==TileID.Lavafall||
            tTile.TileType==TileID.Confetti||tTile.TileType==TileID.ConfettiBlack||tTile.TileType==TileID.CopperCoinPile||tTile.TileType==TileID.SilverCoinPile||
            tTile.TileType==TileID.GoldCoinPile||tTile.TileType==TileID.PlatinumCoinPile||tTile.TileType==TileID.WeaponsRack||tTile.TileType==TileID.FireworksBox||
            tTile.TileType==TileID.LivingFire||tTile.TileType==TileID.AlphabetStatues||tTile.TileType==TileID.FireworkFountain||tTile.TileType==TileID.GrasshopperCage||
            tTile.TileType==TileID.LivingCursedFire||tTile.TileType==TileID.LivingDemonFire||tTile.TileType==TileID.LivingFrostFire||tTile.TileType==TileID.LivingIchor||
            tTile.TileType==TileID.LivingUltrabrightFire||tTile.TileType==TileID.MushroomStatue||tTile.TileType==TileID.ChimneySmoke||tTile.TileType==TileID.CrimsonThorns||
            tTile.TileType==TileID.VineRope||tTile.TileType==TileID.BewitchingTable||tTile.TileType==TileID.AlchemyTable||tTile.TileType==TileID.Sundial||
            tTile.TileType==TileID.GoldBirdCage||tTile.TileType==TileID.GoldBunnyCage||tTile.TileType==TileID.GoldButterflyCage||tTile.TileType==TileID.GoldFrogCage||
            tTile.TileType==TileID.GoldGrasshopperCage||tTile.TileType==TileID.GoldMouseCage||tTile.TileType==TileID.GoldWormCage||tTile.TileType==TileID.SilkRope||
            tTile.TileType==TileID.WebRope||tTile.TileType==TileID.PinkSlimeBlock||tTile.TileType==TileID.PeaceCandle||tTile.TileType==TileID.WaterDrip||
            tTile.TileType==TileID.LavaDrip||tTile.TileType==TileID.HoneyDrip||tTile.TileType==TileID.FishingCrate||tTile.TileType==TileID.SharpeningStation||
            tTile.TileType==TileID.TargetDummy||tTile.TileType==TileID.Bubble||tTile.TileType==TileID.PlanterBox||tTile.TileType==TileID.VineFlowers||
            tTile.TileType==TileID.LavaMoss||tTile.TileType==TileID.VineFlowers||tTile.TileType==TileID.LivingMahogany||tTile.TileType==TileID.LivingMahoganyLeaves||tTile.TileType==TileID.TrapdoorOpen||
            tTile.TileType==TileID.TrapdoorClosed||tTile.TileType==TileID.TallGateClosed||tTile.TileType==TileID.TallGateOpen||tTile.TileType==TileID.LavaLamp||
            tTile.TileType==TileID.CageEnchantedNightcrawler||tTile.TileType==TileID.CageBuggy||tTile.TileType==TileID.CageGrubby||tTile.TileType==TileID.CageSluggy||
            tTile.TileType==TileID.ItemFrame||tTile.TileType==TileID.DesertFossil||tTile.TileType==TileID.Fireplace||tTile.TileType==TileID.Chimney||tTile.TileType==TileID.LunarMonolith||
            tTile.TileType==TileID.Detonator||tTile.TileType==TileID.LunarCraftingStation||tTile.TileType==TileID.SquirrelOrangeCage||tTile.TileType==TileID.SquirrelGoldCage||
            tTile.TileType==TileID.LogicGateLamp||tTile.TileType==TileID.LogicGate||tTile.TileType==TileID.ConveyorBeltLeft||tTile.TileType==TileID.ConveyorBeltRight||
            tTile.TileType==TileID.LogicSensor||tTile.TileType==TileID.WirePipe||tTile.TileType==TileID.AnnouncementBox||tTile.TileType==TileID.TeamBlockRedPlatform||
            tTile.TileType==TileID.WireBulb||tTile.TileType==TileID.TeamBlockGreenPlatform||tTile.TileType==TileID.TeamBlockBluePlatform||tTile.TileType==TileID.TeamBlockYellowPlatform||
            tTile.TileType==TileID.TeamBlockPinkPlatform||tTile.TileType==TileID.TeamBlockWhitePlatform||tTile.TileType==TileID.GemLocks||tTile.TileType==TileID.FakeContainers||
            tTile.TileType==TileID.ProjectilePressurePad||tTile.TileType==TileID.GeyserTrap||tTile.TileType==TileID.BeeHive||tTile.TileType==TileID.PixelBox||
            tTile.TileType==TileID.SillyBalloonPink||tTile.TileType==TileID.SillyBalloonPurple||tTile.TileType==TileID.SillyBalloonGreen||tTile.TileType==TileID.SillyStreamerBlue||
            tTile.TileType==TileID.SillyStreamerGreen||tTile.TileType==TileID.SillyStreamerPink||tTile.TileType==TileID.SillyBalloonMachine||tTile.TileType==TileID.SillyBalloonTile||
            tTile.TileType==TileID.Pigronata||tTile.TileType==TileID.PartyMonolith||tTile.TileType==TileID.PartyBundleOfBalloonTile||tTile.TileType==TileID.PartyPresent||
            tTile.TileType==TileID.SandFallBlock||tTile.TileType==TileID.SnowFallBlock||tTile.TileType==TileID.SnowCloud||tTile.TileType==TileID.SandDrip||tTile.TileType==TileID.DjinnLamp||tTile.TileType==TileID.DefendersForge||
            tTile.TileType==TileID.WarTable||tTile.TileType==TileID.WarTableBanner||tTile.TileType==TileID.ElderCrystalStand||tTile.TileType==TileID.Containers2||
            tTile.TileType==TileID.FakeContainers2||tTile.TileType==TileID.Tables2||tTile.TileType==TileID.DisplayDoll||tTile.TileType==TileID.WeaponsRack2||
            tTile.TileType==TileID.LesionBlock||tTile.TileType==TileID.HatRack||tTile.TileType==TileID.GolfHole||tTile.TileType==TileID.GolfGrass||
            tTile.TileType==TileID.BloodMoonMonolith||tTile.TileType==TileID.CrackedBlueDungeonBrick||tTile.TileType==TileID.CrackedGreenDungeonBrick||tTile.TileType==TileID.CrackedPinkDungeonBrick||
            tTile.TileType==TileID.RollingCactus||tTile.TileType==TileID.AntlionLarva||tTile.TileType==TileID.DrumSet||tTile.TileType==TileID.PicnicTable||
            tTile.TileType==TileID.FallenLog||tTile.TileType==TileID.PinWheel||tTile.TileType==TileID.WeatherVane||tTile.TileType==TileID.GolfGrassHallowed||
            tTile.TileType==TileID.GolfCupFlag||tTile.TileType==TileID.GolfTee||tTile.TileType==TileID.ShellPile||tTile.TileType==TileID.Toilets||
            tTile.TileType==TileID.Spider||tTile.TileType==TileID.LesionStation||tTile.TileType==TileID.MysticSnakeRope||tTile.TileType==TileID.GoldGoldfishBowl||
            tTile.TileType==TileID.CatBast||tTile.TileType==TileID.GoldStarryGlassBlock||tTile.TileType==TileID.BlueStarryGlassBlock||tTile.TileType==TileID.VoidMonolith||tTile.TileType==TileID.ArrowSign||tTile.TileType==TileID.PaintedArrowSign||
            tTile.TileType==TileID.LilyPad||tTile.TileType==TileID.Cattail||tTile.TileType==TileID.FoodPlatter||tTile.TileType==TileID.BlackDragonflyJar||
            tTile.TileType==TileID.BlueDragonflyJar||tTile.TileType==TileID.GreenDragonflyJar||tTile.TileType==TileID.OrangeDragonflyJar||tTile.TileType==TileID.RedDragonflyJar||
            tTile.TileType==TileID.YellowDragonflyJar||tTile.TileType==TileID.GoldDragonflyJar||tTile.TileType==TileID.MushroomVines||tTile.TileType==TileID.SeaOats||
            tTile.TileType==TileID.OasisPlants||tTile.TileType==TileID.BoulderStatue||tTile.TileType==TileID.MaggotCage||tTile.TileType==TileID.RatCage||
            tTile.TileType==TileID.KryptonMoss||tTile.TileType==TileID.XenonMoss||tTile.TileType==TileID.LadybugCage||tTile.TileType==TileID.ArgonMoss||
            tTile.TileType==TileID.OwlCage||tTile.TileType==TileID.PupfishBowl||tTile.TileType==TileID.GoldLadybugCage||tTile.TileType==TileID.LawnFlamingo||
            tTile.TileType==TileID.Grate||tTile.TileType==TileID.PottedPlants1||tTile.TileType==TileID.PottedPlants2||tTile.TileType==TileID.Seaweed||
            tTile.TileType==TileID.TurtleCage||tTile.TileType==TileID.TurtleJungleCage||tTile.TileType==TileID.Sandcastles||tTile.TileType==TileID.GrebeCage||
            tTile.TileType==TileID.SeagullCage||tTile.TileType==TileID.WaterStriderCage||tTile.TileType==TileID.GoldWaterStriderCage||tTile.TileType==TileID.SeahorseCage||
            tTile.TileType==TileID.GoldSeahorseCage||tTile.TileType==TileID.GolfTrophies||tTile.TileType==TileID.MarbleColumn||tTile.TileType==TileID.BambooBlock||
            tTile.TileType==TileID.LargeBambooBlock||tTile.TileType==TileID.PlasmaLamp||tTile.TileType==TileID.FogMachine||tTile.TileType==TileID.GardenGnome||
            tTile.TileType==TileID.PinkFairyJar||tTile.TileType==TileID.GreenFairyJar||tTile.TileType==TileID.BlueFairyJar||tTile.TileType==TileID.Bamboo||
            tTile.TileType==TileID.SoulBottles||tTile.TileType==TileID.TatteredWoodSign||tTile.TileType==TileID.BorealBeam||tTile.TileType==TileID.RichMahoganyBeam||
            tTile.TileType==TileID.GraniteColumn||tTile.TileType==TileID.SandstoneColumn||tTile.TileType==TileID.MushroomBeam||tTile.TileType==TileID.RockGolemHead||
            tTile.TileType==TileID.HellButterflyJar||tTile.TileType==TileID.LavaflyinaBottle||tTile.TileType==TileID.MagmaSnailCage||tTile.TileType==TileID.TreeTopaz||
            tTile.TileType==TileID.TreeAmethyst||tTile.TileType==TileID.TreeSapphire||tTile.TileType==TileID.TreeEmerald||tTile.TileType==TileID.TreeRuby||
            tTile.TileType==TileID.TreeDiamond||tTile.TileType==TileID.TreeAmber||tTile.TileType==TileID.GemSaplings||tTile.TileType==TileID.PotsSuspended||
            tTile.TileType==TileID.BrazierSuspended||tTile.TileType==TileID.VolcanoSmall||tTile.TileType==TileID.VolcanoLarge||tTile.TileType==TileID.VanityTreeSakuraSaplings||
            tTile.TileType==TileID.VanityTreeSakura||tTile.TileType==TileID.TeleportationPylon||tTile.TileType==TileID.LavafishBowl||tTile.TileType==TileID.AmethystBunnyCage||
            tTile.TileType==TileID.TopazBunnyCage||tTile.TileType==TileID.SapphireBunnyCage||tTile.TileType==TileID.EmeraldBunnyCage||tTile.TileType==TileID.RubyBunnyCage||
            tTile.TileType==TileID.DiamondBunnyCage||tTile.TileType==TileID.AmberBunnyCage||tTile.TileType==TileID.AmethystSquirrelCage||tTile.TileType==TileID.TopazSquirrelCage||
            tTile.TileType==TileID.SapphireSquirrelCage||tTile.TileType==TileID.EmeraldSquirrelCage||tTile.TileType==TileID.RubySquirrelCage||tTile.TileType==TileID.DiamondSquirrelCage||
            tTile.TileType==TileID.AmberSquirrelCage||tTile.TileType==TileID.PottedLavaPlants||tTile.TileType==TileID.PottedLavaPlantTendrils||tTile.TileType==TileID.VanityTreeWillowSaplings||
            tTile.TileType==TileID.VanityTreeYellowWillow||tTile.TileType==TileID.MasterTrophyBase||tTile.TileType==TileID.TruffleWormCage||tTile.TileType==TileID.EmpressButterflyJar||
            tTile.TileType==TileID.SliceOfCake||tTile.TileType==TileID.TeaKettle||tTile.TileType==TileID.PottedCrystalPlants||tTile.TileType==TileID.AbigailsFlower||
            tTile.TileType==TileID.VioletMoss||tTile.TileType==TileID.RainbowMoss||tTile.TileType==TileID.StinkbugCage||tTile.TileType==TileID.StinkbugHousingBlocker||
            tTile.TileType==TileID.StinkbugHousingBlockerEcho||tTile.TileType==TileID.ScarletMacawCage||tTile.TileType==TileID.AshGrass||tTile.TileType==TileID.TreeAsh||
            tTile.TileType==TileID.AshWood||tTile.TileType==TileID.CorruptVines||tTile.TileType==TileID.AshPlants||tTile.TileType==TileID.AshVines||tTile.TileType==TileID.ManaCrystal||
            tTile.TileType==TileID.BlueMacawCage||tTile.TileType==TileID.ChlorophyteExtractinator||tTile.TileType==TileID.ToucanCage||tTile.TileType==TileID.YellowCockatielCage||
            tTile.TileType==TileID.GrayCockatielCage||tTile.TileType==TileID.ShadowCandle||tTile.TileType==TileID.LargePilesEcho||tTile.TileType==TileID.LargePiles2Echo||
            tTile.TileType==TileID.SmallPiles2x1Echo||tTile.TileType==TileID.SmallPiles1x1Echo||tTile.TileType==TileID.PlantDetritus3x2Echo||tTile.TileType==TileID.PlantDetritus2x2Echo||
            tTile.TileType==TileID.TNTBarrel||tTile.TileType==TileID.PlanteraThorns||tTile.TileType==TileID.GlowTulip||tTile.TileType==TileID.EchoMonolith||
            tTile.TileType==TileID.ShimmerMonolith||tTile.TileType==TileID.ShimmerflyinaBottle||tTile.TileType==TileID.CorruptJungleGrass||tTile.TileType==TileID.CrimsonJungleGrass||
            tTile.TileType==TileID.Moondial||tTile.TileType==TileID.BouncyBoulder||tTile.TileType==TileID.LifeCrystalBoulder||tTile.TileType==TileID.PoopBlock;
            
        }
    }
}